### ISSUE TITLE
few errors found when running

### ISSUE THREAD

**Issue by ahjolinna** [BillyHalley/harbour-mangasailor#1]
I just run this app and I got few erors, here is the output: http://pastebin.com/vujtzi7m

but works somewhat well, okay its 0.0.1

**Comment by BillyHalley** [comment]
well these are not real error, if the app doesn't crash everything is fine :)

To clarify the xml errors depends on the html file of the page that is downloaded, maybe it's not styled completely as xml, but since it happens at the end of the file is not a problem,
The type error in fact is a problem i always have, but it doesn't interfere with the app, so i don't really care about it
